version: '3'
services:
  girder:
    image: girder/girder:latest
    container_name: girder_jobmock
    network_mode: "host"
    depends_on:
      - 'mongo'
  mongo:
    image: mongo:latest
    container_name: girder_jobmock_mongo
    network_mode: "host"
