version: '3'
services:
  girder:
    image: girder/girder:latest
    container_name: girder_jobmock_dev
    network_mode: "host"
    volumes:
      - ${GIRDER_PATH}:/girder
    depends_on:
      - 'mongo'
  mongo:
    image: mongo:latest
    container_name: girder_jobmock_mongo_dev
    network_mode: "host"
