- hosts: all
  connection: local
  gather_facts: false
  tasks:
    - name: Wait for Girder to come up
      wait_for:
        port: 8080
        delay: 0

    - name: Create 'admin' User
      girder:
        user:
          firstName: "John"
          lastName: "Doe"
          login: "admin"
          password: "letmein"
          email: "admin@admin.com"
          admin: yes
        state: present

    - name: Create filesystem assetstore
      girder:
        username: "admin"
        password: "letmein"
        assetstore:
          name: "Temp Filesystem Assetstore"
          type: "filesystem"
          root: "/data/"
          current: true
        state: present

    - name: Enable thumbnails plugin
      girder:
        username: "admin"
        password: "letmein"
        plugins:
          - jobs
      state: present

    - name: Rebuild the web code
      girder:
        username: "admin"
        password: "letmein"
        post:
          path: "system/web_build"
          data:
            dev: false
      when: development is not defined


    - name: Rebuild the web code (dev)
      girder:
        username: "admin"
        password: "letmein"
        post:
          path: "system/web_build"
          data:
            dev: true
      when: development is defined

    - name: Restart the server
      girder:
        username: "admin"
        password: "letmein"
        put:
          path: "system/restart"

    - name: Wait for Girder to come back up
      wait_for:
        port: 8080
        delay: 0
